server.port=8080
spring.application.name=alert-ingestion-service
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sdapro}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sdapro}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sdapro_secret}
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:sdapro}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:sdapro_secret}
management.endpoints.web.exposure.include=health,info
